"""Clean migration

Revision ID: 067a102509dc
Revises: 
Create Date: 2026-08-14 15:35:03.929301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '067a102509dc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('admin_id', sa.String(length=36), nullable=False),
    sa.Column('admin_name', sa.String(length=150), nullable=False),
    sa.Column('admin_email', sa.String(length=30), nullable=False),
    sa.Column('is_email_verified', sa.Boolean(), nullable=True),
    sa.Column('hash_password', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('admin_id'),
    sa.UniqueConstraint('admin_email')
    )
    op.create_table('categories',
    sa.Column('category_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('class_name', sa.String(length=25), nullable=False),
    sa.Column('class_code', sa.Integer(), nullable=False),
    sa.Column('validated_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('category_id'),
    sa.UniqueConstraint('class_code'),
    sa.UniqueConstraint('class_name')
    )
    op.create_table('training_jobs',
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('class_counts', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('best_model_path', sa.Text(), nullable=True),
    sa.Column('metadata_path', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=30), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('is_email_verified', sa.Boolean(), nullable=True),
    sa.Column('verification_token', sa.Text(), nullable=True),
    sa.Column('reward_points', sa.Integer(), nullable=True),
    sa.Column('image_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('images',
    sa.Column('image_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('temp_s3_path', sa.Text(), nullable=True),
    sa.Column('permanent_s3_path', sa.Text(), nullable=True),
    sa.Column('split_type', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('is_validated', sa.Boolean(), nullable=True),
    sa.Column('reward_given', sa.Boolean(), nullable=True),
    sa.Column('credits_awarded', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('image_id')
    )
    op.create_table('model_versions',
    sa.Column('model_id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=True),
    sa.Column('map_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['training_jobs.job_id'], ),
    sa.PrimaryKeyConstraint('model_id')
    )
    op.create_table('annotations',
    sa.Column('annotation_id', sa.String(length=36), nullable=False),
    sa.Column('image_id', sa.String(length=36), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('annotated_by', sa.String(length=36), nullable=False),
    sa.Column('label_json_path', sa.Text(), nullable=True),
    sa.Column('yolo_label_path', sa.Text(), nullable=True),
    sa.Column('annotated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['annotated_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.category_id'], ),
    sa.ForeignKeyConstraint(['image_id'], ['images.image_id'], ),
    sa.PrimaryKeyConstraint('annotation_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('annotations')
    op.drop_table('model_versions')
    op.drop_table('images')
    op.drop_table('users')
    op.drop_table('training_jobs')
    op.drop_table('categories')
    op.drop_table('admins')
    # ### end Alembic commands ###
